salsify/goldiloader

CHANGELOG.md
goldiloader.gemspec
lib/goldiloader/active_record_patches.rb
lib/goldiloader/compatibility.rb
spec/goldiloader/goldiloader_spec.rb

`CollectionProxy#exists?` should return false for an unpersisted model's association with no values.
This fixes #39
@rlburkes - you're prime

Fix CollectionProxy#exists?

---

CHANGELOG.md
lib/goldiloader/active_record_patches.rb
spec/db/schema.rb
spec/goldiloader/goldiloader_spec.rb

Pass block to ActiveRecord::Relation#exec_queries to fix inverse_of in Rails 5.x. Fixes #42.
@rlburkes - you're prime

Pass block to ActiveRecord::Relation#exec_queries

---

.travis.yml
CHANGELOG.md
README.md
goldiloader.gemspec
lib/goldiloader/active_record_patches.rb

This PR add Goldiloader support for Rails 5.1. The only change of interest was fallout from rails/rails#26200 which removed methods affected by the `fully_load` setting from `ActiveRecord::Associations::CollectionAssociation` in favor of methods in `ActiveRecord::Associations::CollectionProxy`. Fortunately we can just override the `ActiveRecord::Associations::CollectionAssociation#find_from_target?` method to do the right thing.
The conditionals based on Rails versions continue to be a mess. At some point I'll cut a 1.0 release and then start working on a 2.0 release the drops support for older versions of Rails (likely 3.2, 4.0 and 4.1).
@rlburkes - you're prime

Rails 5.1 Support

---

.travis.yml
CHANGELOG.md
README.md
goldiloader.gemspec
lib/goldiloader/active_record_patches.rb
lib/goldiloader/association_info.rb
lib/goldiloader/association_loader.rb
lib/goldiloader/association_options.rb
lib/goldiloader/compatibility.rb
spec/db/schema.rb
spec/goldiloader/goldiloader_spec.rb

This PR drops support for Rails 3.2/4.0/4.1 and Ruby 1.9/2.0. This allowed us to drop lots of code and conditionals needed to support old versions of Rails. I'm going to switch the monkey patching over to use `Module#prepend` in another PR.
@tjwp - you're prime

Drop support for old versions of Ruby/Rails

---

CHANGELOG.md
README.md
lib/goldiloader/active_record_patches.rb
lib/goldiloader/association_info.rb
lib/goldiloader/association_options.rb
lib/goldiloader/compatibility.rb
spec/db/schema.rb
spec/goldiloader/goldiloader_spec.rb

This PR adds an `auto_include` query scope method to disable automatic eager loading for individual queries e.g.
```ruby
Blog.order(:name).auto_include(false)
```
It also removes the `auto_include` association option in favor of using the query scope method (which we can do now that we dropped Rails 3.2 support). The migration path will be:
```ruby
class Blog < ActiveRecord::Base
has_many :posts, auto_include: false
has_many :posts, -> { auto_include(false) }
end
```
@tjwp - you're prime

Add auto_include query scope method

---

goldiloader.gemspec

Add links to changelog, bug tracker, etc. in the gemspec.
@atsheehan - you're prime

Add links in gemspec

---

.travis.yml
Appraisals
CHANGELOG.md
README.md
gemfiles/rails_5.0.gemfile
gemfiles/rails_5.1.gemfile
gemfiles/rails_5.2.gemfile
goldiloader.gemspec
lib/goldiloader/active_record_patches.rb
lib/goldiloader/compatibility.rb
lib/goldiloader/version.rb
spec/goldiloader/goldiloader_spec.rb

The only interesting change was a workaround for https://github.com/rails/rails/pull/32375 which prevents automatic eagerloading from working on destroyed models. Also note activerecord-jdbc-adapter doesn't yet support Rails 5.2 so I had to disable those tests.
Fixes #63.

Rails 5.2 Support

---

README.md

Also wondering if "from" can be removed from the list for Rails 5.2+ due to [this fix](https://github.com/rails/rails/pull/29413)

Link to referenced Rails bug in README

---

CHANGELOG.md
README.md
lib/goldiloader/active_record_patches.rb
lib/goldiloader/compatibility.rb
lib/goldiloader/version.rb
spec/goldiloader/goldiloader_spec.rb

Enable eager loading of associations with a `from` in Rails 5.0.x >= 5.0.7 and Rails >= 5.1.5 because the underlying Rails bug has been fixed.

Enable eager loading of associations with a from

---

CHANGELOG.md
README.md
lib/goldiloader/active_record_patches.rb
lib/goldiloader/compatibility.rb
spec/goldiloader/goldiloader_spec.rb

Enable eager loading of associations with a `group` in Rails 5.0.x >= 5.0.7 and Rails >= 5.1.5 because the underlying Rails bug has been fixed.

Enable eager loading of associations with a  group

---

lib/goldiloader/active_record_patches.rb
lib/goldiloader/association_info.rb
spec/db/schema.rb
spec/goldiloader/goldiloader_spec.rb

Since has one associations with an order clause indicates that the
database may have more than one record, we can't auto eager load those.
Closes #61

Do not auto eager load has one associations with order

---

.travis.yml
CHANGELOG.md
README.md
goldiloader.gemspec
lib/goldiloader/version.rb

I hit some issues enabling Rubocop for this project with old version of Ruby. Fortunately their EOL so we can just drop support for them :)

Drop support for Ruby <= 2.2

---

CHANGELOG.md
lib/goldiloader/compatibility.rb
lib/goldiloader/version.rb

Enable eager loading of associations on destroyed models in all versions of Rails except 5.2.0 since
Rails issue [32375](https://github.com/rails/rails/pull/32375) has been fixed.

Enable eager loading of associations on destroyed models in Rails 5.2.1+

---

CHANGELOG.md
lib/goldiloader/active_record_patches.rb

This reorders some of the predicates in `AssociationPatch#eager_loadable?` so Ruby can short circuit more of the evaluation for common cases.
@rrunyon - you're prime

Optimize checks to see if an association is eager loadable

---

CHANGELOG.md
lib/goldiloader/compatibility.rb
lib/goldiloader/version.rb
spec/goldiloader/goldiloader_spec.rb

I'm silly and inverted the condition in https://github.com/salsify/goldiloader/pull/74 :(
@fgarces - you're prime

Fix eager loading associations on destroyed models

---

benchmark/db/schema.rb
benchmark/main.rb
goldiloader.gemspec

My result:
```
→ ruby benchmark/main.rb
-- create_table(:blogs, {:force=>true})
-> 0.0035s
-- create_table(:posts, {:force=>true})
-> 0.0004s
-- create_table(:users, {:force=>true})
-> 0.0003s
-- create_table(:addresses, {:force=>true})
-> 0.0003s
-- create_table(:groups, {:force=>true})
-> 0.0003s
-- create_table(:tags, {:force=>true})
-> 0.0003s
-- create_table(:post_tags, {:force=>true})
-> 0.0003s
user     system      total        real
AR eager loading:      0.017352   0.000509   0.017861 (  0.017874)
AR with goldiloader:   0.032490   0.000850   0.033340 (  0.033918)
```

Add benchamark

---

.travis.yml
README.md

Rails 6.0 requires Ruby 2.5+. I also bumped the MRI point releases we're testing with and add Ruby 2.6 tests while I was in here.

Don't test Rails Edge with Ruby 2.4

---

gemfiles/rails_4.2.gemfile
goldiloader.gemspec

This builds are failing now that sqlite3 1.4.0 has been released because Rails has an [explicit dependency](https://github.com/rails/rails/blob/v5.2.2/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb#L12) on this version of sqlite3 that isn't declared in its gemspec. See https://github.com/rails/rails/issues/35153 for more info. For now the easiest thing to do is pin the tests to sqlite3 1.3.x.

Fix build failure from new sqlite version

---

Appraisals
gemfiles/rails_4.2.gemfile
gemfiles/rails_5.0.gemfile
gemfiles/rails_5.1.gemfile
gemfiles/rails_5.2.gemfile
goldiloader.gemspec

Now that https://github.com/rails/rails/issues/35153 has been fixed in Rails 5.1+ we can use a less restrict version specifier for the sqlite development dependency. This fixes the sqlite errors we were hitting in Rails Edge builds but now Rails Edge builds are failing for a different reason. I'll fix that in another PR.

Upgrade to versions of Rails with more flexible sqlite dependencies

---

.rubocop.yml
.travis.yml
spec/spec_helper.rb

Enable Travis' gem [caching](https://docs.travis-ci.com/user/caching/) to cut CI time 30%. Note I had to update the rubocop config to exclude the gems that are not being installed in the vendor directory.

Enable Travis gem caching

---

.travis.yml
Appraisals
gemfiles/rails_4.2.gemfile
gemfiles/rails_5.2.gemfile
gemfiles/rails_6.0.gemfile

This upgrades the test matrix to the latest versions of Ruby and Rails. It also drops testing of EOL Ruby 2.3 and 2.4 and adds testing with Ruby 2.7.

Upgrade Test Matrix

---

.circleci/config.yml
Appraisals
CHANGELOG.md
README.md
gemfiles/rails_6.1.gemfile
goldiloader.gemspec
lib/goldiloader/version.rb

This PR adds official support for Rails 6.1 and bumps our testing of Rails Edge to be compatible with Rails 6.2.
Fixes #97 #98

Rails 6.1 support

---

CHANGELOG.md
lib/goldiloader/association_loader.rb
lib/goldiloader/compatibility.rb
lib/goldiloader/version.rb

The Rails internal `ActiveRecord::Associations::Preloader` API changed in https://github.com/rails/rails/pull/40776 so we need to make a corresponding change in goldiloader.

Fix Rails Edge for changes in ActiveRecord::Associations::Preloader API

---

Appraisals
gemfiles/rails_edge.gemfile

Rails changed their default branch from `master` to `main` so we need to make a corresponding change to our CI builds.

Fix Rails edge builds

---

spec/goldiloader/goldiloader_spec.rb
spec/spec_helper.rb

Rails Edge changed the implementation of `ActiveRecord::Relation` to call `ActiveRecord::Base. _query_by_sql` rather than `ActiveRecord::Base. find_by_sql` in commit [2a90104989b9f1653337d08871610d394b2d626d](https://github.com/rails/rails/commit/2a90104989b9f1653337d08871610d394b2d626d#diff-18a561656864ea240daf46bdb1f50faace49f9ef74b90bcf667d9bbb17fce084R923) which broke a bunch of tests that rely on spying on calls to `ActiveRecord::Base. find_by_sql`. This PR fixes the failing tests by using an ActiveSupport subscriber on [sql.active_record](https://guides.rubyonrails.org/active_support_instrumentation.html#sql-active-record) events to spy on query execution. This should make the tests more resilient to future changes in Rails and avoids introducing a dependency on a 3rd party gem.

Fix Rails Edge tests

---

CHANGELOG.md
lib/goldiloader/active_record_patches.rb
lib/goldiloader/version.rb
spec/db/schema.rb
spec/goldiloader/goldiloader_spec.rb

This PR fixes an issue that caused loading polymorphic associations with scopes to raise an error as described in #105. Our checking to see if an association could be eager loaded relied on the target class of the association to evaluate the association's scope block and then look for problematic constructs like offsets or limits. This doesn't work for polymorphic associations because the target association class won't be known outside the context of a given association instance.
The fix is to defer the computation as to whether or not an association is eager loadable until we know the association instance's target class but retain the performance optimizations from #78 by caching this information.
Fixes #105.
/cc @luizkowalski

Handle polymorphic associations with scopes

---

README.md
lib/goldiloader.rb
lib/goldiloader/active_record_patches.rb
spec/goldiloader/goldiloader_spec.rb

Fixes #55
This patch enables the auto loading via 
```ruby
Goldiloader.auto_include do
end
```
Based on the work of @gzunigal

Add configuration option for disabling automatic eager loading

---

lib/goldiloader.rb
spec/goldiloader/goldiloader_spec.rb

This fixes a subtle bug that can cause unpredictable behavior if `globally_enabled` is changed (i.e. during app initialization).
With the current code, whenever `enabled` or `disabled` is called with a block, the previous value is restored to the thread local variable. However, if the previous value was not set, then the value that is stored is the value of `globally_enabled`.
Consider this contrived example:
```ruby
Goldiloader.globally_enabled = true
ThreadPool.run do
Goldiloader.enabled { do_thing } # Thread[: goldiloader_enabled] now set to true in this thread
end
Goldiloader.globally_enabled = false
ThreadPool.run do
Goldiloader.enabled { do_thing } # Thread[: goldiloader_enabled] now set to false in this thread
end
```
Now, assuming we had two different threads running in the thread …

Do not persist globally enabled in threads

---

.circleci/config.yml
Appraisals
CHANGELOG.md
README.md
gemfiles/rails_6.1.gemfile
gemfiles/rails_7.0.gemfile
goldiloader.gemspec
lib/goldiloader/version.rb

This PR adds support for Rails 7.0 and Ruby 3.1. It also bumps the test matrix to use the latest point releases of Ruby/Rails.

Rails 7.0/Ruby 3.1 Support

---

.circleci/config.yml

This PR adds Ruby 3.2 to the test matrix and bumps the patch versions for the other Ruby versions.

Add Ruby 3.2 to the test matrix

---

README.md
lib/goldiloader.rb
lib/goldiloader/active_record_patches.rb
lib/goldiloader/auto_include_context.rb
lib/goldiloader/custom_preloads.rb
spec/db/schema.rb
spec/goldiloader/goldiloader_spec.rb
spec/spec_helper.rb

Referenced Issue: #128 
This PR implements the idea that I outlined in the mentioned issue. 
I was thinking of moving the logic into its own class (e.g. `auto_include_context.custom_preloads.some_method`), but that would require to also pass the `@models` to that instance. So I ended up including the logic in the `AutoIncludeContext` to keep the memory footprint as low as possible.
Refer to the Readme changes for usage instructions. Please let me know if there's anything should be adjusted (code styling etc.).

Implement custom preloads

---

README.md
lib/goldiloader/custom_preloads.rb
spec/goldiloader/goldiloader_spec.rb

Hi,
the idea of this PR is to allow custom preloads with multiple keys without adding a dedicated method for the the combined key.
In order to do so, you can just pass an array of symbols as the `key:` argument. Instead of passing a plain array of ids to the block, we would collect an array of keys for each record and pass the 2 dimensional array to the block.
This is 100% backwards compatible.

Custom preloads with multiple keys

---

README.md

Hi there,
Thank you for this gem. Here at CareMessage, we have been using it for a while with great results.
Today we would like to give back to the community our workaround for the case of has_one/has_many associations with SQL limit.
The implementation still needs an SQL lateral join. However, it can get simpler by replacing the extra view and model with a single parameter in the has_one/has_many definition.
We have tested out this example in a Rails app here, and apparently it works well.

Simplified LATERAL join example in README

---

.circleci/config.yml
Appraisals
README.md
gemfiles/rails_7.1.gemfile

I forgot to actually add Rails 7.1 to the test matrix in #127 🤦‍♂️
While I was in here I removed some references to older versions of Rails in the README.
@erikkessler1 - you're prime

Add Rails 7.1 to test matrix

---

lib/goldiloader/active_record_patches.rb
spec/goldiloader/goldiloader_spec.rb

When an association goes through another association, e.g. `has_many :tags, through: :post_tags`, loading the `post_tags` association was enough, to not auto include the `tags` association when it is first accessed.
This is correct for when the `post_tags` association was modified and auto include could lead to weird results. When nothing was modified it is totally fine to auto include the through association.
Consider the following data model and data:
```ruby
class Post < ActiveRecord::Base
has_many :post_tags
has_many :tags, through: :post_tags
end
class PostTags < ActiveRecord::Base
belongs_to :post
belongs_to :tag
end
class Tags < ActiveRecord::Base
has_many :post_tags
has_many :posts, through: :post_tags
end
blog = Blog.create!(name: 'blog')
post1 = Post.create(blog: blog, title: …
```

Auto include through associations when 'middle' association was loaded but not modified

---

CHANGELOG.md
lib/goldiloader.rb
lib/goldiloader/active_record_patches.rb
lib/goldiloader/association_options.rb
lib/goldiloader/compatibility.rb
lib/goldiloader/version.rb

This PR defers referencing any ActiveRecord classes until the framework has been initialized to ensure the `Rails.application.config.filter_parameters` setting is applied properly. Unfortunately our usage of [combustion](https://github.com/pat/combustion) makes it impossible to add automated test coverage but I've manually verified the fix using https://github.com/jturkel/rails-test-app.
Fixes #140
prime: @erikkessler1

Use ActiveRecord lazy load hooks

---

.circleci/config.yml
Appraisals
CHANGELOG.md
gemfiles/rails_7.2.gemfile
goldiloader.gemspec
lib/goldiloader/version.rb

This PR releases official support for Rails 7.2. Also following the suggestion of @kyrofa in #154, I changed the gemspec Rails version constraint to `< 8` so we can test against `8.0.0.alpha` on `main` without claiming support `8.0.0`.
@erikkessler1 - you're prime

Official Rails 7.2.0 Support

---

.circleci/config.yml
Appraisals
gemfiles/rails_6.1.gemfile
gemfiles/rails_7.0.gemfile
gemfiles/rails_7.1.gemfile
goldiloader.gemspec

Rails 7.2 added support for sqlite3 2.x. Rails 8.0 will require sqlite3 2.x. This PR updates our test configuration to reflect that which will fix the failing Rails edge tests.

Test against sqlite3 2.0 for Rails 7.2+

---

lib/goldiloader/active_record_patches.rb

Today this uses Ruby 2-era argument forwarding that doesn't separate out keyword arguments in Ruby 3. This PR fixes #157 by updating the forwarding technique to be compatible with Ruby 3.

active record patches: use Ruby 3 argument forwarding
